### =========================================================================
### 1. Получить список всех пользователей (клиентов и курьеров)
### =========================================================================
GET http://localhost:8080/api/users

### =========================================================================
### 2. Профиль пользователя #2 (ПЕРВЫЙ ВЫЗОВ -> CACHE MISS)
### Ожидаем: "fromCache": false (данные из PostgreSQL кладутся в кэш Riak)
### =========================================================================
GET http://localhost:8080/api/users/2

### =========================================================================
### 3. Профиль пользователя #2 (ВТОРОЙ ВЫЗОВ -> CACHE HIT!)
### Ожидаем: "fromCache": true (кэш Riak KV) и "visitCount" увеличился на +1
### =========================================================================
GET http://localhost:8080/api/users/2

### =========================================================================
### 4. Вход оператора
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "operator1"
}

> {%
    client.global.set("auth_token", response.body.token);
    client.log("Автоматически сохранен токен сессии: " + response.body.token);
%}

### =========================================================================
### 5. Проверка активности сессии оператора
### =========================================================================
GET http://localhost:8080/api/auth/session
X-Session-Token: {{auth_token}}

### =========================================================================
### 6. Отправка уведомления клиенту
###  логируется в историю действий в Riak KV

POST http://localhost:8080/api/users/2/notify
Content-Type: application/json
X-Session-Token: {{auth_token}}

{
  "message": "Эксперимент 3: riak22,riak3 остановлен",
  "type": "WARNING"
}

### =========================================================================
### 7. Просмотр истории действий пользователя
### Ожидаем: JSON-массив событий из Riak KV с отправленным уведомлением
### =========================================================================
GET http://localhost:8080/api/users/2/history

### =========================================================================
### 8. Редактирование профиля (Инвалидация кэша в Riak KV)
### =========================================================================
PUT http://localhost:8080/api/users/2
Content-Type: application/json
X-Session-Token: {{auth_token}}

{
  "fullName": "Иван Кузнецов",
  "phone": "+7-999-777-88-99",
  "deliveryAddress": "г. Москва, ул. Арбат, д. 10, кв. 5"
}

### =========================================================================
### 9. Проверка инвалидации кэша после редактирования
### Ожидаем: "fromCache": false (старый кэш удален, прочитано из Postgres)
### =========================================================================
GET http://localhost:8080/api/users/2

### =========================================================================
### 10. Выход оператора (Удаление сессии из Riak KV)
### =========================================================================
POST http://localhost:8080/api/auth/logout
X-Session-Token: {{auth_token}}

### =========================================================================
### 11. Проверка сессии после выхода (Ожидаем 401 Unauthorized)

GET http://localhost:8080/api/auth/session
X-Session-Token: {{auth_token}}