
server.port=8080
spring.application.name=nosqllab1


spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/food_delivery_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


riak.nodes=localhost:8087,localhost:8088,localhost:8089